[package]
name = "chaos"
version = "0.1.0"
authors = ["Underslash12 <stew_smith@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.19"
colorsys = "0.6.7"
